# NeetCode 150, grouped by roadmap category in recommended order.
# Source: neetcode.io/roadmap category ordering.

NEETCODE_150 = [
    ("Arrays & Hashing", [
        ("Contains Duplicate", "Easy", "https://leetcode.com/problems/contains-duplicate/"),
        ("Valid Anagram", "Easy", "https://leetcode.com/problems/valid-anagram/"),
        ("Two Sum", "Easy", "https://leetcode.com/problems/two-sum/"),
        ("Group Anagrams", "Medium", "https://leetcode.com/problems/group-anagrams/"),
        ("Top K Frequent Elements", "Medium", "https://leetcode.com/problems/top-k-frequent-elements/"),
        ("Product of Array Except Self", "Medium", "https://leetcode.com/problems/product-of-array-except-self/"),
        ("Valid Sudoku", "Medium", "https://leetcode.com/problems/valid-sudoku/"),
        ("Encode and Decode Strings", "Medium", "https://leetcode.com/problems/encode-and-decode-strings/"),
        ("Longest Consecutive Sequence", "Medium", "https://leetcode.com/problems/longest-consecutive-sequence/"),
    ]),
    ("Two Pointers", [
        ("Valid Palindrome", "Easy", "https://leetcode.com/problems/valid-palindrome/"),
        ("Two Sum II - Input Array Is Sorted", "Medium", "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/"),
        ("3Sum", "Medium", "https://leetcode.com/problems/3sum/"),
        ("Container With Most Water", "Medium", "https://leetcode.com/problems/container-with-most-water/"),
        ("Trapping Rain Water", "Hard", "https://leetcode.com/problems/trapping-rain-water/"),
    ]),
    ("Sliding Window", [
        ("Best Time to Buy and Sell Stock", "Easy", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"),
        ("Longest Substring Without Repeating Characters", "Medium", "https://leetcode.com/problems/longest-substring-without-repeating-characters/"),
        ("Longest Repeating Character Replacement", "Medium", "https://leetcode.com/problems/longest-repeating-character-replacement/"),
        ("Permutation in String", "Medium", "https://leetcode.com/problems/permutation-in-string/"),
        ("Minimum Window Substring", "Hard", "https://leetcode.com/problems/minimum-window-substring/"),
        ("Sliding Window Maximum", "Hard", "https://leetcode.com/problems/sliding-window-maximum/"),
    ]),
    ("Stack", [
        ("Valid Parentheses", "Easy", "https://leetcode.com/problems/valid-parentheses/"),
        ("Min Stack", "Medium", "https://leetcode.com/problems/min-stack/"),
        ("Evaluate Reverse Polish Notation", "Medium", "https://leetcode.com/problems/evaluate-reverse-polish-notation/"),
        ("Generate Parentheses", "Medium", "https://leetcode.com/problems/generate-parentheses/"),
        ("Daily Temperatures", "Medium", "https://leetcode.com/problems/daily-temperatures/"),
        ("Car Fleet", "Medium", "https://leetcode.com/problems/car-fleet/"),
        ("Largest Rectangle in Histogram", "Hard", "https://leetcode.com/problems/largest-rectangle-in-histogram/"),
    ]),
    ("Binary Search", [
        ("Binary Search", "Easy", "https://leetcode.com/problems/binary-search/"),
        ("Search a 2D Matrix", "Medium", "https://leetcode.com/problems/search-a-2d-matrix/"),
        ("Koko Eating Bananas", "Medium", "https://leetcode.com/problems/koko-eating-bananas/"),
        ("Find Minimum in Rotated Sorted Array", "Medium", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"),
        ("Search in Rotated Sorted Array", "Medium", "https://leetcode.com/problems/search-in-rotated-sorted-array/"),
        ("Time Based Key-Value Store", "Medium", "https://leetcode.com/problems/time-based-key-value-store/"),
        ("Median of Two Sorted Arrays", "Hard", "https://leetcode.com/problems/median-of-two-sorted-arrays/"),
    ]),
    ("Linked List", [
        ("Reverse Linked List", "Easy", "https://leetcode.com/problems/reverse-linked-list/"),
        ("Merge Two Sorted Lists", "Easy", "https://leetcode.com/problems/merge-two-sorted-lists/"),
        ("Linked List Cycle", "Easy", "https://leetcode.com/problems/linked-list-cycle/"),
        ("Reorder List", "Medium", "https://leetcode.com/problems/reorder-list/"),
        ("Remove Nth Node From End of List", "Medium", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"),
        ("Copy List with Random Pointer", "Medium", "https://leetcode.com/problems/copy-list-with-random-pointer/"),
        ("Add Two Numbers", "Medium", "https://leetcode.com/problems/add-two-numbers/"),
        ("Find the Duplicate Number", "Medium", "https://leetcode.com/problems/find-the-duplicate-number/"),
        ("LRU Cache", "Medium", "https://leetcode.com/problems/lru-cache/"),
        ("Merge k Sorted Lists", "Hard", "https://leetcode.com/problems/merge-k-sorted-lists/"),
        ("Reverse Nodes in k-Group", "Hard", "https://leetcode.com/problems/reverse-nodes-in-k-group/"),
    ]),
    ("Trees", [
        ("Invert Binary Tree", "Easy", "https://leetcode.com/problems/invert-binary-tree/"),
        ("Maximum Depth of Binary Tree", "Easy", "https://leetcode.com/problems/maximum-depth-of-binary-tree/"),
        ("Diameter of Binary Tree", "Easy", "https://leetcode.com/problems/diameter-of-binary-tree/"),
        ("Balanced Binary Tree", "Easy", "https://leetcode.com/problems/balanced-binary-tree/"),
        ("Same Tree", "Easy", "https://leetcode.com/problems/same-tree/"),
        ("Subtree of Another Tree", "Easy", "https://leetcode.com/problems/subtree-of-another-tree/"),
        ("Lowest Common Ancestor of a Binary Search Tree", "Medium", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"),
        ("Binary Tree Level Order Traversal", "Medium", "https://leetcode.com/problems/binary-tree-level-order-traversal/"),
        ("Binary Tree Right Side View", "Medium", "https://leetcode.com/problems/binary-tree-right-side-view/"),
        ("Count Good Nodes in Binary Tree", "Medium", "https://leetcode.com/problems/count-good-nodes-in-binary-tree/"),
        ("Validate Binary Search Tree", "Medium", "https://leetcode.com/problems/validate-binary-search-tree/"),
        ("Kth Smallest Element in a BST", "Medium", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/"),
        ("Construct Binary Tree from Preorder and Inorder Traversal", "Medium", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"),
        ("Binary Tree Maximum Path Sum", "Hard", "https://leetcode.com/problems/binary-tree-maximum-path-sum/"),
        ("Serialize and Deserialize Binary Tree", "Hard", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"),
    ]),
    ("Tries", [
        ("Implement Trie (Prefix Tree)", "Medium", "https://leetcode.com/problems/implement-trie-prefix-tree/"),
        ("Design Add and Search Words Data Structure", "Medium", "https://leetcode.com/problems/add-and-search-word-data-structure-design/"),
        ("Word Search II", "Hard", "https://leetcode.com/problems/word-search-ii/"),
    ]),
    ("Heap / Priority Queue", [
        ("Kth Largest Element in a Stream", "Easy", "https://leetcode.com/problems/kth-largest-element-in-a-stream/"),
        ("Last Stone Weight", "Easy", "https://leetcode.com/problems/last-stone-weight/"),
        ("K Closest Points to Origin", "Medium", "https://leetcode.com/problems/k-closest-points-to-origin/"),
        ("Kth Largest Element in an Array", "Medium", "https://leetcode.com/problems/kth-largest-element-in-an-array/"),
        ("Task Scheduler", "Medium", "https://leetcode.com/problems/task-scheduler/"),
        ("Design Twitter", "Medium", "https://leetcode.com/problems/design-twitter/"),
        ("Find Median from Data Stream", "Hard", "https://leetcode.com/problems/find-median-from-data-stream/"),
    ]),
    ("Backtracking", [
        ("Subsets", "Medium", "https://leetcode.com/problems/subsets/"),
        ("Combination Sum", "Medium", "https://leetcode.com/problems/combination-sum/"),
        ("Combination Sum II", "Medium", "https://leetcode.com/problems/combination-sum-ii/"),
        ("Permutations", "Medium", "https://leetcode.com/problems/permutations/"),
        ("Subsets II", "Medium", "https://leetcode.com/problems/subsets-ii/"),
        ("Word Search", "Medium", "https://leetcode.com/problems/word-search/"),
        ("Palindrome Partitioning", "Medium", "https://leetcode.com/problems/palindrome-partitioning/"),
        ("Letter Combinations of a Phone Number", "Medium", "https://leetcode.com/problems/letter-combinations-of-a-phone-number/"),
        ("N-Queens", "Hard", "https://leetcode.com/problems/n-queens/"),
    ]),
    ("Graphs", [
        ("Number of Islands", "Medium", "https://leetcode.com/problems/number-of-islands/"),
        ("Max Area of Island", "Medium", "https://leetcode.com/problems/max-area-of-island/"),
        ("Clone Graph", "Medium", "https://leetcode.com/problems/clone-graph/"),
        ("Walls and Gates", "Medium", "https://leetcode.com/problems/walls-and-gates/"),
        ("Rotting Oranges", "Medium", "https://leetcode.com/problems/rotting-oranges/"),
        ("Pacific Atlantic Water Flow", "Medium", "https://leetcode.com/problems/pacific-atlantic-water-flow/"),
        ("Surrounded Regions", "Medium", "https://leetcode.com/problems/surrounded-regions/"),
        ("Course Schedule", "Medium", "https://leetcode.com/problems/course-schedule/"),
        ("Course Schedule II", "Medium", "https://leetcode.com/problems/course-schedule-ii/"),
        ("Graph Valid Tree", "Medium", "https://leetcode.com/problems/graph-valid-tree/"),
        ("Number of Connected Components in an Undirected Graph", "Medium", "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/"),
        ("Redundant Connection", "Medium", "https://leetcode.com/problems/redundant-connection/"),
        ("Word Ladder", "Hard", "https://leetcode.com/problems/word-ladder/"),
        ("Reconstruct Itinerary", "Hard", "https://leetcode.com/problems/reconstruct-itinerary/"),
        ("Min Cost to Connect All Points", "Medium", "https://leetcode.com/problems/min-cost-to-connect-all-points/"),
        ("Network Delay Time", "Medium", "https://leetcode.com/problems/network-delay-time/"),
        ("Swim in Rising Water", "Hard", "https://leetcode.com/problems/swim-in-rising-water/"),
        ("Alien Dictionary", "Hard", "https://leetcode.com/problems/alien-dictionary/"),
        ("Cheapest Flights Within K Stops", "Medium", "https://leetcode.com/problems/cheapest-flights-within-k-stops/"),
    ]),
    ("1-D Dynamic Programming", [
        ("Climbing Stairs", "Easy", "https://leetcode.com/problems/climbing-stairs/"),
        ("Min Cost Climbing Stairs", "Easy", "https://leetcode.com/problems/min-cost-climbing-stairs/"),
        ("House Robber", "Medium", "https://leetcode.com/problems/house-robber/"),
        ("House Robber II", "Medium", "https://leetcode.com/problems/house-robber-ii/"),
        ("Longest Palindromic Substring", "Medium", "https://leetcode.com/problems/longest-palindromic-substring/"),
        ("Palindromic Substrings", "Medium", "https://leetcode.com/problems/palindromic-substrings/"),
        ("Decode Ways", "Medium", "https://leetcode.com/problems/decode-ways/"),
        ("Coin Change", "Medium", "https://leetcode.com/problems/coin-change/"),
        ("Maximum Product Subarray", "Medium", "https://leetcode.com/problems/maximum-product-subarray/"),
        ("Word Break", "Medium", "https://leetcode.com/problems/word-break/"),
        ("Longest Increasing Subsequence", "Medium", "https://leetcode.com/problems/longest-increasing-subsequence/"),
        ("Partition Equal Subset Sum", "Medium", "https://leetcode.com/problems/partition-equal-subset-sum/"),
    ]),
    ("2-D Dynamic Programming", [
        ("Unique Paths", "Medium", "https://leetcode.com/problems/unique-paths/"),
        ("Longest Common Subsequence", "Medium", "https://leetcode.com/problems/longest-common-subsequence/"),
        ("Best Time to Buy and Sell Stock with Cooldown", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/"),
        ("Coin Change II", "Medium", "https://leetcode.com/problems/coin-change-ii/"),
        ("Target Sum", "Medium", "https://leetcode.com/problems/target-sum/"),
        ("Interleaving String", "Medium", "https://leetcode.com/problems/interleaving-string/"),
        ("Longest Increasing Path in a Matrix", "Hard", "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/"),
        ("Distinct Subsequences", "Hard", "https://leetcode.com/problems/distinct-subsequences/"),
        ("Edit Distance", "Medium", "https://leetcode.com/problems/edit-distance/"),
        ("Burst Balloons", "Hard", "https://leetcode.com/problems/burst-balloons/"),
        ("Regular Expression Matching", "Hard", "https://leetcode.com/problems/regular-expression-matching/"),
    ]),
    ("Greedy", [
        ("Maximum Subarray", "Medium", "https://leetcode.com/problems/maximum-subarray/"),
        ("Jump Game", "Medium", "https://leetcode.com/problems/jump-game/"),
        ("Jump Game II", "Medium", "https://leetcode.com/problems/jump-game-ii/"),
        ("Gas Station", "Medium", "https://leetcode.com/problems/gas-station/"),
        ("Hand of Straights", "Medium", "https://leetcode.com/problems/hand-of-straights/"),
        ("Merge Triplets to Form Target Triplet", "Medium", "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/"),
        ("Partition Labels", "Medium", "https://leetcode.com/problems/partition-labels/"),
        ("Valid Parenthesis String", "Medium", "https://leetcode.com/problems/valid-parenthesis-string/"),
    ]),
    ("Intervals", [
        ("Insert Interval", "Medium", "https://leetcode.com/problems/insert-interval/"),
        ("Merge Intervals", "Medium", "https://leetcode.com/problems/merge-intervals/"),
        ("Non-overlapping Intervals", "Medium", "https://leetcode.com/problems/non-overlapping-intervals/"),
        ("Meeting Rooms", "Easy", "https://leetcode.com/problems/meeting-rooms/"),
        ("Meeting Rooms II", "Medium", "https://leetcode.com/problems/meeting-rooms-ii/"),
        ("Minimum Interval to Include Each Query", "Hard", "https://leetcode.com/problems/minimum-interval-to-include-each-query/"),
    ]),
    ("Math & Geometry", [
        ("Rotate Image", "Medium", "https://leetcode.com/problems/rotate-image/"),
        ("Spiral Matrix", "Medium", "https://leetcode.com/problems/spiral-matrix/"),
        ("Set Matrix Zeroes", "Medium", "https://leetcode.com/problems/set-matrix-zeroes/"),
        ("Happy Number", "Easy", "https://leetcode.com/problems/happy-number/"),
        ("Plus One", "Easy", "https://leetcode.com/problems/plus-one/"),
        ("Pow(x, n)", "Medium", "https://leetcode.com/problems/powx-n/"),
        ("Multiply Strings", "Medium", "https://leetcode.com/problems/multiply-strings/"),
        ("Detect Squares", "Medium", "https://leetcode.com/problems/detect-squares/"),
    ]),
    ("Bit Manipulation", [
        ("Single Number", "Easy", "https://leetcode.com/problems/single-number/"),
        ("Number of 1 Bits", "Easy", "https://leetcode.com/problems/number-of-1-bits/"),
        ("Counting Bits", "Easy", "https://leetcode.com/problems/counting-bits/"),
        ("Reverse Bits", "Easy", "https://leetcode.com/problems/reverse-bits/"),
        ("Missing Number", "Easy", "https://leetcode.com/problems/missing-number/"),
        ("Sum of Two Integers", "Medium", "https://leetcode.com/problems/sum-of-two-integers/"),
        ("Reverse Integer", "Medium", "https://leetcode.com/problems/reverse-integer/"),
    ]),
]
