# NeetCode 250, grouped by neetcode.io category (roadmap order).
# This is NeetCode 150 plus the additional ~100 problems. Categorized and
# cross-checked against the per-category totals published on neetcode.io's
# NeetCode 250 practice page. A couple of judgment calls were needed where
# NeetCode doesn't publish a raw problem-by-problem list -- if you spot a
# mismatch against the live roadmap, it's easiest to just edit this file
# directly and re-deploy; existing progress is matched by LeetCode URL, so
# reordering or tweaking entries here won't wipe your review history.

NEETCODE_250 = [
    ("Arrays & Hashing", [
        ("Contains Duplicate", "Easy", "https://leetcode.com/problems/contains-duplicate/"),
        ("Valid Anagram", "Easy", "https://leetcode.com/problems/valid-anagram/"),
        ("Two Sum", "Easy", "https://leetcode.com/problems/two-sum/"),
        ("Group Anagrams", "Medium", "https://leetcode.com/problems/group-anagrams/"),
        ("Top K Frequent Elements", "Medium", "https://leetcode.com/problems/top-k-frequent-elements/"),
        ("Product of Array Except Self", "Medium", "https://leetcode.com/problems/product-of-array-except-self/"),
        ("Valid Sudoku", "Medium", "https://leetcode.com/problems/valid-sudoku/"),
        ("Encode and Decode Strings", "Medium", "https://leetcode.com/problems/encode-and-decode-strings/"),
        ("Longest Consecutive Sequence", "Medium", "https://leetcode.com/problems/longest-consecutive-sequence/"),
        ("Concatenation of Array", "Easy", "https://leetcode.com/problems/concatenation-of-array/"),
        ("Sort an Array", "Medium", "https://leetcode.com/problems/sort-an-array/"),
        ("Longest Common Prefix", "Easy", "https://leetcode.com/problems/longest-common-prefix/"),
        ("Remove Element", "Easy", "https://leetcode.com/problems/remove-element/"),
        ("Majority Element", "Easy", "https://leetcode.com/problems/majority-element/"),
        ("Sort Colors", "Medium", "https://leetcode.com/problems/sort-colors/"),
        ("Design HashSet", "Easy", "https://leetcode.com/problems/design-hashset/"),
        ("Design HashMap", "Easy", "https://leetcode.com/problems/design-hashmap/"),
        ("Range Sum Query 2D - Immutable", "Medium", "https://leetcode.com/problems/range-sum-query-2d-immutable/"),
        ("Best Time to Buy and Sell Stock II", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/"),
        ("Majority Element II", "Medium", "https://leetcode.com/problems/majority-element-ii"),
        ("Subarray Sum Equals K", "Medium", "https://leetcode.com/problems/subarray-sum-equals-k/"),
        ("First Missing Positive", "Hard", "https://leetcode.com/problems/first-missing-positive/"),
    ]),
    ("Two Pointers", [
        ("Valid Palindrome", "Easy", "https://leetcode.com/problems/valid-palindrome/"),
        ("Two Sum II - Input Array Is Sorted", "Medium", "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/"),
        ("3Sum", "Medium", "https://leetcode.com/problems/3sum/"),
        ("Container With Most Water", "Medium", "https://leetcode.com/problems/container-with-most-water/"),
        ("Trapping Rain Water", "Hard", "https://leetcode.com/problems/trapping-rain-water/"),
        ("Reverse String", "Easy", "https://leetcode.com/problems/reverse-string/"),
        ("Valid Palindrome II", "Easy", "https://leetcode.com/problems/valid-palindrome-ii/"),
        ("4Sum", "Medium", "https://leetcode.com/problems/4sum/"),
        ("Merge Strings Alternately", "Easy", "https://leetcode.com/problems/merge-strings-alternately/"),
        ("Rotate Array", "Medium", "https://leetcode.com/problems/rotate-array/"),
        ("Merge Sorted Array", "Easy", "https://leetcode.com/problems/merge-sorted-array/"),
        ("Remove Duplicates From Sorted Array", "Easy", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/"),
        ("Boats to Save People", "Medium", "https://leetcode.com/problems/boats-to-save-people/"),
    ]),
    ("Sliding Window", [
        ("Best Time to Buy and Sell Stock", "Easy", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"),
        ("Longest Substring Without Repeating Characters", "Medium", "https://leetcode.com/problems/longest-substring-without-repeating-characters/"),
        ("Longest Repeating Character Replacement", "Medium", "https://leetcode.com/problems/longest-repeating-character-replacement/"),
        ("Permutation in String", "Medium", "https://leetcode.com/problems/permutation-in-string/"),
        ("Minimum Window Substring", "Hard", "https://leetcode.com/problems/minimum-window-substring/"),
        ("Sliding Window Maximum", "Hard", "https://leetcode.com/problems/sliding-window-maximum/"),
        ("Contains Duplicate II", "Easy", "https://leetcode.com/problems/contains-duplicate-ii/"),
        ("Minimum Size Subarray Sum", "Medium", "https://leetcode.com/problems/minimum-size-subarray-sum/"),
        ("Find K Closest Elements", "Medium", "https://leetcode.com/problems/find-k-closest-elements/"),
    ]),
    ("Stack", [
        ("Valid Parentheses", "Easy", "https://leetcode.com/problems/valid-parentheses/"),
        ("Min Stack", "Medium", "https://leetcode.com/problems/min-stack/"),
        ("Evaluate Reverse Polish Notation", "Medium", "https://leetcode.com/problems/evaluate-reverse-polish-notation/"),
        ("Generate Parentheses", "Medium", "https://leetcode.com/problems/generate-parentheses/"),
        ("Daily Temperatures", "Medium", "https://leetcode.com/problems/daily-temperatures/"),
        ("Car Fleet", "Medium", "https://leetcode.com/problems/car-fleet/"),
        ("Largest Rectangle in Histogram", "Hard", "https://leetcode.com/problems/largest-rectangle-in-histogram/"),
        ("Baseball Game", "Easy", "https://leetcode.com/problems/baseball-game/"),
        ("Implement Stack using Queues", "Easy", "https://leetcode.com/problems/implement-stack-using-queues/"),
        ("Asteroid Collision", "Medium", "https://leetcode.com/problems/asteroid-collision/"),
        ("Online Stock Span", "Medium", "https://leetcode.com/problems/online-stock-span/"),
        ("Simplify Path", "Medium", "https://leetcode.com/problems/simplify-path/"),
        ("Decode String", "Medium", "https://leetcode.com/problems/decode-string/"),
        ("Maximum Frequency Stack", "Hard", "https://leetcode.com/problems/maximum-frequency-stack/"),
    ]),
    ("Binary Search", [
        ("Binary Search", "Easy", "https://leetcode.com/problems/binary-search/"),
        ("Search a 2D Matrix", "Medium", "https://leetcode.com/problems/search-a-2d-matrix/"),
        ("Koko Eating Bananas", "Medium", "https://leetcode.com/problems/koko-eating-bananas/"),
        ("Find Minimum in Rotated Sorted Array", "Medium", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"),
        ("Search in Rotated Sorted Array", "Medium", "https://leetcode.com/problems/search-in-rotated-sorted-array/"),
        ("Time Based Key-Value Store", "Medium", "https://leetcode.com/problems/time-based-key-value-store/"),
        ("Median of Two Sorted Arrays", "Hard", "https://leetcode.com/problems/median-of-two-sorted-arrays/"),
        ("Search Insert Position", "Easy", "https://leetcode.com/problems/search-insert-position/"),
        ("Guess Number Higher or Lower", "Easy", "https://leetcode.com/problems/guess-number-higher-or-lower/"),
        ("Sqrt(x)", "Easy", "https://leetcode.com/problems/sqrtx/"),
        ("Capacity To Ship Packages Within D Days", "Medium", "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/"),
        ("Search in Rotated Sorted Array II", "Medium", "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/"),
        ("Split Array Largest Sum", "Hard", "https://leetcode.com/problems/split-array-largest-sum/"),
        ("Find in Mountain Array", "Hard", "https://leetcode.com/problems/find-in-mountain-array"),
    ]),
    ("Linked List", [
        ("Reverse Linked List", "Easy", "https://leetcode.com/problems/reverse-linked-list/"),
        ("Merge Two Sorted Lists", "Easy", "https://leetcode.com/problems/merge-two-sorted-lists/"),
        ("Linked List Cycle", "Easy", "https://leetcode.com/problems/linked-list-cycle/"),
        ("Reorder List", "Medium", "https://leetcode.com/problems/reorder-list/"),
        ("Remove Nth Node From End of List", "Medium", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/"),
        ("Copy List with Random Pointer", "Medium", "https://leetcode.com/problems/copy-list-with-random-pointer/"),
        ("Add Two Numbers", "Medium", "https://leetcode.com/problems/add-two-numbers/"),
        ("Find the Duplicate Number", "Medium", "https://leetcode.com/problems/find-the-duplicate-number/"),
        ("LRU Cache", "Medium", "https://leetcode.com/problems/lru-cache/"),
        ("Merge k Sorted Lists", "Hard", "https://leetcode.com/problems/merge-k-sorted-lists/"),
        ("Reverse Nodes in k-Group", "Hard", "https://leetcode.com/problems/reverse-nodes-in-k-group/"),
        ("Reverse Linked List II", "Medium", "https://leetcode.com/problems/reverse-linked-list-ii/"),
        ("Design Circular Queue", "Medium", "https://leetcode.com/problems/design-circular-queue/"),
        ("LFU Cache", "Hard", "https://leetcode.com/problems/lfu-cache/"),
    ]),
    ("Trees", [
        ("Invert Binary Tree", "Easy", "https://leetcode.com/problems/invert-binary-tree/"),
        ("Maximum Depth of Binary Tree", "Easy", "https://leetcode.com/problems/maximum-depth-of-binary-tree/"),
        ("Diameter of Binary Tree", "Easy", "https://leetcode.com/problems/diameter-of-binary-tree/"),
        ("Balanced Binary Tree", "Easy", "https://leetcode.com/problems/balanced-binary-tree/"),
        ("Same Tree", "Easy", "https://leetcode.com/problems/same-tree/"),
        ("Subtree of Another Tree", "Easy", "https://leetcode.com/problems/subtree-of-another-tree/"),
        ("Lowest Common Ancestor of a Binary Search Tree", "Medium", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"),
        ("Binary Tree Level Order Traversal", "Medium", "https://leetcode.com/problems/binary-tree-level-order-traversal/"),
        ("Binary Tree Right Side View", "Medium", "https://leetcode.com/problems/binary-tree-right-side-view/"),
        ("Count Good Nodes in Binary Tree", "Medium", "https://leetcode.com/problems/count-good-nodes-in-binary-tree/"),
        ("Validate Binary Search Tree", "Medium", "https://leetcode.com/problems/validate-binary-search-tree/"),
        ("Kth Smallest Element in a BST", "Medium", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/"),
        ("Construct Binary Tree from Preorder and Inorder Traversal", "Medium", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"),
        ("Binary Tree Maximum Path Sum", "Hard", "https://leetcode.com/problems/binary-tree-maximum-path-sum/"),
        ("Serialize and Deserialize Binary Tree", "Hard", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"),
        ("Binary Tree Inorder Traversal", "Easy", "https://leetcode.com/problems/binary-tree-inorder-traversal/"),
        ("Binary Tree Preorder Traversal", "Easy", "https://leetcode.com/problems/binary-tree-preorder-traversal/"),
        ("Insert into a Binary Search Tree", "Medium", "https://leetcode.com/problems/insert-into-a-binary-search-tree/"),
        ("Binary Tree Postorder Traversal", "Easy", "https://leetcode.com/problems/binary-tree-postorder-traversal/"),
        ("Delete Node in a BST", "Medium", "https://leetcode.com/problems/delete-node-in-a-bst/"),
        ("Construct Quad Tree", "Medium", "https://leetcode.com/problems/construct-quad-tree/"),
        ("Delete Leaves With a Given Value", "Medium", "https://leetcode.com/problems/delete-leaves-with-a-given-value"),
        ("House Robber III", "Medium", "https://leetcode.com/problems/house-robber-iii/"),
    ]),
    ("Heap / Priority Queue", [
        ("Kth Largest Element in a Stream", "Easy", "https://leetcode.com/problems/kth-largest-element-in-a-stream/"),
        ("Last Stone Weight", "Easy", "https://leetcode.com/problems/last-stone-weight/"),
        ("K Closest Points to Origin", "Medium", "https://leetcode.com/problems/k-closest-points-to-origin/"),
        ("Kth Largest Element in an Array", "Medium", "https://leetcode.com/problems/kth-largest-element-in-an-array/"),
        ("Task Scheduler", "Medium", "https://leetcode.com/problems/task-scheduler/"),
        ("Design Twitter", "Medium", "https://leetcode.com/problems/design-twitter/"),
        ("Find Median from Data Stream", "Hard", "https://leetcode.com/problems/find-median-from-data-stream/"),
        ("Single-Threaded CPU", "Medium", "https://leetcode.com/problems/single-threaded-cpu/"),
        ("Reorganize String", "Medium", "https://leetcode.com/problems/reorganize-string/"),
        ("Longest Happy String", "Medium", "https://leetcode.com/problems/longest-happy-string/"),
        ("Car Pooling", "Medium", "https://leetcode.com/problems/car-pooling/"),
        ("IPO", "Hard", "https://leetcode.com/problems/ipo/"),
    ]),
    ("Backtracking", [
        ("Subsets", "Medium", "https://leetcode.com/problems/subsets/"),
        ("Combination Sum", "Medium", "https://leetcode.com/problems/combination-sum/"),
        ("Combination Sum II", "Medium", "https://leetcode.com/problems/combination-sum-ii/"),
        ("Permutations", "Medium", "https://leetcode.com/problems/permutations/"),
        ("Subsets II", "Medium", "https://leetcode.com/problems/subsets-ii/"),
        ("Word Search", "Medium", "https://leetcode.com/problems/word-search/"),
        ("Palindrome Partitioning", "Medium", "https://leetcode.com/problems/palindrome-partitioning/"),
        ("Letter Combinations of a Phone Number", "Medium", "https://leetcode.com/problems/letter-combinations-of-a-phone-number/"),
        ("N-Queens", "Hard", "https://leetcode.com/problems/n-queens/"),
        ("Sum of All Subsets XOR Total", "Easy", "https://leetcode.com/problems/sum-of-all-subset-xor-totals"),
        ("Combinations", "Medium", "https://leetcode.com/problems/combinations/"),
        ("Combination Sum III", "Medium", "https://leetcode.com/problems/combination-sum-iii/"),
        ("Permutations II", "Medium", "https://leetcode.com/problems/permutations-ii/"),
        ("Matchsticks to Square", "Medium", "https://leetcode.com/problems/matchsticks-to-square/"),
        ("Partition to K Equal Sum Subsets", "Medium", "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/"),
        ("N-Queens II", "Hard", "https://leetcode.com/problems/n-queens-ii/"),
        ("Word Break II", "Hard", "https://leetcode.com/problems/word-break-ii"),
    ]),
    ("Tries", [
        ("Implement Trie (Prefix Tree)", "Medium", "https://leetcode.com/problems/implement-trie-prefix-tree/"),
        ("Design Add and Search Words Data Structure", "Medium", "https://leetcode.com/problems/add-and-search-word-data-structure-design/"),
        ("Word Search II", "Hard", "https://leetcode.com/problems/word-search-ii/"),
        ("Extra Characters in a String", "Medium", "https://leetcode.com/problems/extra-characters-in-a-string/"),
    ]),
    ("Graphs", [
        ("Number of Islands", "Medium", "https://leetcode.com/problems/number-of-islands/"),
        ("Max Area of Island", "Medium", "https://leetcode.com/problems/max-area-of-island/"),
        ("Clone Graph", "Medium", "https://leetcode.com/problems/clone-graph/"),
        ("Walls and Gates", "Medium", "https://leetcode.com/problems/walls-and-gates/"),
        ("Rotting Oranges", "Medium", "https://leetcode.com/problems/rotting-oranges/"),
        ("Pacific Atlantic Water Flow", "Medium", "https://leetcode.com/problems/pacific-atlantic-water-flow/"),
        ("Surrounded Regions", "Medium", "https://leetcode.com/problems/surrounded-regions/"),
        ("Course Schedule", "Medium", "https://leetcode.com/problems/course-schedule/"),
        ("Course Schedule II", "Medium", "https://leetcode.com/problems/course-schedule-ii/"),
        ("Graph Valid Tree", "Medium", "https://leetcode.com/problems/graph-valid-tree/"),
        ("Number of Connected Components in an Undirected Graph", "Medium", "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/"),
        ("Redundant Connection", "Medium", "https://leetcode.com/problems/redundant-connection/"),
        ("Word Ladder", "Hard", "https://leetcode.com/problems/word-ladder/"),
        ("Island Perimeter", "Easy", "https://leetcode.com/problems/island-perimeter/"),
        ("Verifying an Alien Dictionary", "Easy", "https://leetcode.com/problems/verifying-an-alien-dictionary/"),
        ("Find the Town Judge", "Easy", "https://leetcode.com/problems/find-the-town-judge"),
        ("Open the Lock", "Medium", "https://leetcode.com/problems/open-the-lock/"),
        ("Course Schedule IV", "Medium", "https://leetcode.com/problems/course-schedule-iv/"),
        ("Accounts Merge", "Medium", "https://leetcode.com/problems/accounts-merge/"),
        ("Evaluate Division", "Medium", "https://leetcode.com/problems/evaluate-division/"),
        ("Minimum Height Trees", "Medium", "https://leetcode.com/problems/minimum-height-trees"),
    ]),
    ("Advanced Graphs", [
        ("Path With Minimum Effort", "Medium", "https://leetcode.com/problems/path-with-minimum-effort/"),
        ("Network Delay Time", "Medium", "https://leetcode.com/problems/network-delay-time/"),
        ("Min Cost to Connect All Points", "Medium", "https://leetcode.com/problems/min-cost-to-connect-all-points/"),
        ("Cheapest Flights Within K Stops", "Medium", "https://leetcode.com/problems/cheapest-flights-within-k-stops/"),
        ("Reconstruct Itinerary", "Hard", "https://leetcode.com/problems/reconstruct-itinerary/"),
        ("Swim in Rising Water", "Hard", "https://leetcode.com/problems/swim-in-rising-water/"),
        ("Alien Dictionary", "Hard", "https://leetcode.com/problems/alien-dictionary/"),
        ("Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree", "Hard", "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/"),
        ("Build a Matrix With Conditions", "Hard", "https://leetcode.com/problems/build-a-matrix-with-conditions"),
        ("Greatest Common Divisor Traversal", "Hard", "https://leetcode.com/problems/greatest-common-divisor-traversal"),
    ]),
    ("1-D Dynamic Programming", [
        ("Climbing Stairs", "Easy", "https://leetcode.com/problems/climbing-stairs/"),
        ("Min Cost Climbing Stairs", "Easy", "https://leetcode.com/problems/min-cost-climbing-stairs/"),
        ("House Robber", "Medium", "https://leetcode.com/problems/house-robber/"),
        ("House Robber II", "Medium", "https://leetcode.com/problems/house-robber-ii/"),
        ("Longest Palindromic Substring", "Medium", "https://leetcode.com/problems/longest-palindromic-substring/"),
        ("Palindromic Substrings", "Medium", "https://leetcode.com/problems/palindromic-substrings/"),
        ("Decode Ways", "Medium", "https://leetcode.com/problems/decode-ways/"),
        ("Coin Change", "Medium", "https://leetcode.com/problems/coin-change/"),
        ("Maximum Product Subarray", "Medium", "https://leetcode.com/problems/maximum-product-subarray/"),
        ("Word Break", "Medium", "https://leetcode.com/problems/word-break/"),
        ("Longest Increasing Subsequence", "Medium", "https://leetcode.com/problems/longest-increasing-subsequence/"),
        ("Partition Equal Subset Sum", "Medium", "https://leetcode.com/problems/partition-equal-subset-sum/"),
        ("N-th Tribonacci Number", "Easy", "https://leetcode.com/problems/n-th-tribonacci-number/"),
        ("Combination Sum IV", "Medium", "https://leetcode.com/problems/combination-sum-iv/"),
        ("Perfect Squares", "Medium", "https://leetcode.com/problems/perfect-squares/"),
        ("Integer Break", "Medium", "https://leetcode.com/problems/integer-break/"),
        ("Stone Game III", "Hard", "https://leetcode.com/problems/stone-game-iii/"),
    ]),
    ("2-D Dynamic Programming", [
        ("Unique Paths", "Medium", "https://leetcode.com/problems/unique-paths/"),
        ("Longest Common Subsequence", "Medium", "https://leetcode.com/problems/longest-common-subsequence/"),
        ("Best Time to Buy and Sell Stock with Cooldown", "Medium", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/"),
        ("Coin Change II", "Medium", "https://leetcode.com/problems/coin-change-ii/"),
        ("Target Sum", "Medium", "https://leetcode.com/problems/target-sum/"),
        ("Interleaving String", "Medium", "https://leetcode.com/problems/interleaving-string/"),
        ("Longest Increasing Path in a Matrix", "Hard", "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/"),
        ("Distinct Subsequences", "Hard", "https://leetcode.com/problems/distinct-subsequences/"),
        ("Edit Distance", "Medium", "https://leetcode.com/problems/edit-distance/"),
        ("Burst Balloons", "Hard", "https://leetcode.com/problems/burst-balloons/"),
        ("Regular Expression Matching", "Hard", "https://leetcode.com/problems/regular-expression-matching/"),
        ("Unique Paths II", "Medium", "https://leetcode.com/problems/unique-paths-ii/"),
        ("Minimum Path Sum", "Medium", "https://leetcode.com/problems/minimum-path-sum/"),
        ("Last Stone Weight II", "Medium", "https://leetcode.com/problems/last-stone-weight-ii/"),
        ("Stone Game", "Medium", "https://leetcode.com/problems/stone-game/"),
        ("Stone Game II", "Medium", "https://leetcode.com/problems/stone-game-ii/"),
    ]),
    ("Greedy", [
        ("Maximum Subarray", "Medium", "https://leetcode.com/problems/maximum-subarray/"),
        ("Jump Game", "Medium", "https://leetcode.com/problems/jump-game/"),
        ("Jump Game II", "Medium", "https://leetcode.com/problems/jump-game-ii/"),
        ("Gas Station", "Medium", "https://leetcode.com/problems/gas-station/"),
        ("Hand of Straights", "Medium", "https://leetcode.com/problems/hand-of-straights/"),
        ("Merge Triplets to Form Target Triplet", "Medium", "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/"),
        ("Partition Labels", "Medium", "https://leetcode.com/problems/partition-labels/"),
        ("Valid Parenthesis String", "Medium", "https://leetcode.com/problems/valid-parenthesis-string/"),
        ("Lemonade Change", "Easy", "https://leetcode.com/problems/lemonade-change/"),
        ("Maximum Sum Circular Subarray", "Medium", "https://leetcode.com/problems/maximum-sum-circular-subarray/"),
        ("Longest Turbulent Subarray", "Medium", "https://leetcode.com/problems/longest-turbulent-subarray/"),
        ("Jump Game VII", "Medium", "https://leetcode.com/problems/jump-game-vii/"),
        ("Dota2 Senate", "Medium", "https://leetcode.com/problems/dota2-senate/"),
        ("Candy", "Hard", "https://leetcode.com/problems/candy/"),
    ]),
    ("Intervals", [
        ("Insert Interval", "Medium", "https://leetcode.com/problems/insert-interval/"),
        ("Merge Intervals", "Medium", "https://leetcode.com/problems/merge-intervals/"),
        ("Non-overlapping Intervals", "Medium", "https://leetcode.com/problems/non-overlapping-intervals/"),
        ("Meeting Rooms", "Easy", "https://leetcode.com/problems/meeting-rooms/"),
        ("Meeting Rooms II", "Medium", "https://leetcode.com/problems/meeting-rooms-ii/"),
        ("Minimum Interval to Include Each Query", "Hard", "https://leetcode.com/problems/minimum-interval-to-include-each-query/"),
        ("Meeting Rooms III", "Hard", "https://leetcode.com/problems/meeting-rooms-iii"),
    ]),
    ("Math & Geometry", [
        ("Rotate Image", "Medium", "https://leetcode.com/problems/rotate-image/"),
        ("Spiral Matrix", "Medium", "https://leetcode.com/problems/spiral-matrix/"),
        ("Set Matrix Zeroes", "Medium", "https://leetcode.com/problems/set-matrix-zeroes/"),
        ("Happy Number", "Easy", "https://leetcode.com/problems/happy-number/"),
        ("Plus One", "Easy", "https://leetcode.com/problems/plus-one/"),
        ("Pow(x, n)", "Medium", "https://leetcode.com/problems/powx-n/"),
        ("Multiply Strings", "Medium", "https://leetcode.com/problems/multiply-strings/"),
        ("Detect Squares", "Medium", "https://leetcode.com/problems/detect-squares/"),
        ("Excel Sheet Column Title", "Easy", "https://leetcode.com/problems/excel-sheet-column-title/"),
        ("Insert Greatest Common Divisors in Linked List", "Medium", "https://leetcode.com/problems/insert-greatest-common-divisors-in-linked-list/"),
        ("Greatest Common Divisor of Strings", "Easy", "https://leetcode.com/problems/greatest-common-divisor-of-strings/"),
        ("Transpose Matrix", "Easy", "https://leetcode.com/problems/transpose-matrix"),
        ("Roman to Integer", "Easy", "https://leetcode.com/problems/roman-to-integer/"),
    ]),
    ("Bit Manipulation", [
        ("Single Number", "Easy", "https://leetcode.com/problems/single-number/"),
        ("Number of 1 Bits", "Easy", "https://leetcode.com/problems/number-of-1-bits/"),
        ("Counting Bits", "Easy", "https://leetcode.com/problems/counting-bits/"),
        ("Reverse Bits", "Easy", "https://leetcode.com/problems/reverse-bits/"),
        ("Missing Number", "Easy", "https://leetcode.com/problems/missing-number/"),
        ("Sum of Two Integers", "Medium", "https://leetcode.com/problems/sum-of-two-integers/"),
        ("Reverse Integer", "Medium", "https://leetcode.com/problems/reverse-integer/"),
        ("Bitwise AND of Numbers Range", "Medium", "https://leetcode.com/problems/bitwise-and-of-numbers-range"),
        ("Add Binary", "Easy", "https://leetcode.com/problems/add-binary/"),
        ("Minimum Array End", "Medium", "https://leetcode.com/problems/minimum-array-end/"),
    ]),
]


# The original NeetCode 150 URLs -- used to tag which of the 250 problems
# count toward the core goal vs. the bonus pool. Kept as a URL set (rather
# than a second full duplicate list) since the full problem data already
# lives in NEETCODE_250 above.
CORE_150_URLS = {
    "https://leetcode.com/problems/contains-duplicate/",
    "https://leetcode.com/problems/valid-anagram/",
    "https://leetcode.com/problems/two-sum/",
    "https://leetcode.com/problems/group-anagrams/",
    "https://leetcode.com/problems/top-k-frequent-elements/",
    "https://leetcode.com/problems/product-of-array-except-self/",
    "https://leetcode.com/problems/valid-sudoku/",
    "https://leetcode.com/problems/encode-and-decode-strings/",
    "https://leetcode.com/problems/longest-consecutive-sequence/",
    "https://leetcode.com/problems/valid-palindrome/",
    "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    "https://leetcode.com/problems/3sum/",
    "https://leetcode.com/problems/container-with-most-water/",
    "https://leetcode.com/problems/trapping-rain-water/",
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "https://leetcode.com/problems/permutation-in-string/",
    "https://leetcode.com/problems/minimum-window-substring/",
    "https://leetcode.com/problems/sliding-window-maximum/",
    "https://leetcode.com/problems/valid-parentheses/",
    "https://leetcode.com/problems/min-stack/",
    "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    "https://leetcode.com/problems/generate-parentheses/",
    "https://leetcode.com/problems/daily-temperatures/",
    "https://leetcode.com/problems/car-fleet/",
    "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "https://leetcode.com/problems/binary-search/",
    "https://leetcode.com/problems/search-a-2d-matrix/",
    "https://leetcode.com/problems/koko-eating-bananas/",
    "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "https://leetcode.com/problems/time-based-key-value-store/",
    "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "https://leetcode.com/problems/reverse-linked-list/",
    "https://leetcode.com/problems/merge-two-sorted-lists/",
    "https://leetcode.com/problems/linked-list-cycle/",
    "https://leetcode.com/problems/reorder-list/",
    "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "https://leetcode.com/problems/copy-list-with-random-pointer/",
    "https://leetcode.com/problems/add-two-numbers/",
    "https://leetcode.com/problems/find-the-duplicate-number/",
    "https://leetcode.com/problems/lru-cache/",
    "https://leetcode.com/problems/merge-k-sorted-lists/",
    "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    "https://leetcode.com/problems/invert-binary-tree/",
    "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "https://leetcode.com/problems/diameter-of-binary-tree/",
    "https://leetcode.com/problems/balanced-binary-tree/",
    "https://leetcode.com/problems/same-tree/",
    "https://leetcode.com/problems/subtree-of-another-tree/",
    "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "https://leetcode.com/problems/binary-tree-right-side-view/",
    "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
    "https://leetcode.com/problems/validate-binary-search-tree/",
    "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "https://leetcode.com/problems/implement-trie-prefix-tree/",
    "https://leetcode.com/problems/add-and-search-word-data-structure-design/",
    "https://leetcode.com/problems/word-search-ii/",
    "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    "https://leetcode.com/problems/last-stone-weight/",
    "https://leetcode.com/problems/k-closest-points-to-origin/",
    "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "https://leetcode.com/problems/task-scheduler/",
    "https://leetcode.com/problems/design-twitter/",
    "https://leetcode.com/problems/find-median-from-data-stream/",
    "https://leetcode.com/problems/subsets/",
    "https://leetcode.com/problems/combination-sum/",
    "https://leetcode.com/problems/combination-sum-ii/",
    "https://leetcode.com/problems/permutations/",
    "https://leetcode.com/problems/subsets-ii/",
    "https://leetcode.com/problems/word-search/",
    "https://leetcode.com/problems/palindrome-partitioning/",
    "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    "https://leetcode.com/problems/n-queens/",
    "https://leetcode.com/problems/number-of-islands/",
    "https://leetcode.com/problems/max-area-of-island/",
    "https://leetcode.com/problems/clone-graph/",
    "https://leetcode.com/problems/walls-and-gates/",
    "https://leetcode.com/problems/rotting-oranges/",
    "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    "https://leetcode.com/problems/surrounded-regions/",
    "https://leetcode.com/problems/course-schedule/",
    "https://leetcode.com/problems/course-schedule-ii/",
    "https://leetcode.com/problems/graph-valid-tree/",
    "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    "https://leetcode.com/problems/redundant-connection/",
    "https://leetcode.com/problems/word-ladder/",
    "https://leetcode.com/problems/reconstruct-itinerary/",
    "https://leetcode.com/problems/min-cost-to-connect-all-points/",
    "https://leetcode.com/problems/network-delay-time/",
    "https://leetcode.com/problems/swim-in-rising-water/",
    "https://leetcode.com/problems/alien-dictionary/",
    "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    "https://leetcode.com/problems/climbing-stairs/",
    "https://leetcode.com/problems/min-cost-climbing-stairs/",
    "https://leetcode.com/problems/house-robber/",
    "https://leetcode.com/problems/house-robber-ii/",
    "https://leetcode.com/problems/longest-palindromic-substring/",
    "https://leetcode.com/problems/palindromic-substrings/",
    "https://leetcode.com/problems/decode-ways/",
    "https://leetcode.com/problems/coin-change/",
    "https://leetcode.com/problems/maximum-product-subarray/",
    "https://leetcode.com/problems/word-break/",
    "https://leetcode.com/problems/longest-increasing-subsequence/",
    "https://leetcode.com/problems/partition-equal-subset-sum/",
    "https://leetcode.com/problems/unique-paths/",
    "https://leetcode.com/problems/longest-common-subsequence/",
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
    "https://leetcode.com/problems/coin-change-ii/",
    "https://leetcode.com/problems/target-sum/",
    "https://leetcode.com/problems/interleaving-string/",
    "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    "https://leetcode.com/problems/distinct-subsequences/",
    "https://leetcode.com/problems/edit-distance/",
    "https://leetcode.com/problems/burst-balloons/",
    "https://leetcode.com/problems/regular-expression-matching/",
    "https://leetcode.com/problems/maximum-subarray/",
    "https://leetcode.com/problems/jump-game/",
    "https://leetcode.com/problems/jump-game-ii/",
    "https://leetcode.com/problems/gas-station/",
    "https://leetcode.com/problems/hand-of-straights/",
    "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
    "https://leetcode.com/problems/partition-labels/",
    "https://leetcode.com/problems/valid-parenthesis-string/",
    "https://leetcode.com/problems/insert-interval/",
    "https://leetcode.com/problems/merge-intervals/",
    "https://leetcode.com/problems/non-overlapping-intervals/",
    "https://leetcode.com/problems/meeting-rooms/",
    "https://leetcode.com/problems/meeting-rooms-ii/",
    "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
    "https://leetcode.com/problems/rotate-image/",
    "https://leetcode.com/problems/spiral-matrix/",
    "https://leetcode.com/problems/set-matrix-zeroes/",
    "https://leetcode.com/problems/happy-number/",
    "https://leetcode.com/problems/plus-one/",
    "https://leetcode.com/problems/powx-n/",
    "https://leetcode.com/problems/multiply-strings/",
    "https://leetcode.com/problems/detect-squares/",
    "https://leetcode.com/problems/single-number/",
    "https://leetcode.com/problems/number-of-1-bits/",
    "https://leetcode.com/problems/counting-bits/",
    "https://leetcode.com/problems/reverse-bits/",
    "https://leetcode.com/problems/missing-number/",
    "https://leetcode.com/problems/sum-of-two-integers/",
    "https://leetcode.com/problems/reverse-integer/",
}


# One-time seed for the companies/problem_companies tables (see init_db() in
# app.py), sourced from a community-maintained aggregation of user-reported
# interview experiences (github.com/liquidslr/leetcode-company-wise-problems,
# scoped to ~18 well-known tech companies). Only used the first time this
# feature boots -- after that, companies and tags are fully user-managed via
# the API, so editing this dict won't retroactively change anyone's tags.
COMPANY_TAGS_SEED = {
    "https://leetcode.com/problems/3sum/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok",
    "https://leetcode.com/problems/4sum/": "Amazon, Apple, Bloomberg, DoorDash, Google, Meta, Microsoft, Nvidia",
    "https://leetcode.com/problems/accounts-merge/": "Airbnb, Amazon, Bloomberg, Goldman Sachs, Google, TikTok, Uber",
    "https://leetcode.com/problems/add-and-search-word-data-structure-design/": "Amazon, Apple, Bloomberg, DoorDash, Google, LinkedIn, Oracle, TikTok",
    "https://leetcode.com/problems/add-binary/": "Adobe, Amazon, Apple, Bloomberg, Google, Meta, Microsoft",
    "https://leetcode.com/problems/add-two-numbers/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/alien-dictionary/": "Airbnb, Amazon, Apple, Bloomberg, Google, TikTok, Uber",
    "https://leetcode.com/problems/asteroid-collision/": "Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/balanced-binary-tree/": "Amazon, Apple, Bloomberg, Google, Meta",
    "https://leetcode.com/problems/baseball-game/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, TikTok",
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/": "Amazon, Apple, Bloomberg, Google, TikTok",
    "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/binary-search/": "Amazon, Bloomberg, Google, Oracle",
    "https://leetcode.com/problems/binary-tree-inorder-traversal/": "Amazon, Bloomberg, Google, Meta, Microsoft",
    "https://leetcode.com/problems/binary-tree-level-order-traversal/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Oracle",
    "https://leetcode.com/problems/binary-tree-maximum-path-sum/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/binary-tree-postorder-traversal/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/binary-tree-preorder-traversal/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/binary-tree-right-side-view/": "Amazon, Apple, Bloomberg, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/bitwise-and-of-numbers-range": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/boats-to-save-people/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/build-a-matrix-with-conditions": "Google",
    "https://leetcode.com/problems/burst-balloons/": "Amazon, Bloomberg, Goldman Sachs, Google, Salesforce, Uber",
    "https://leetcode.com/problems/candy/": "Amazon, Bloomberg, Goldman Sachs, Google, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/car-fleet/": "Amazon, Bloomberg, Goldman Sachs, Google",
    "https://leetcode.com/problems/car-pooling/": "Amazon, Bloomberg, Goldman Sachs, Google",
    "https://leetcode.com/problems/cheapest-flights-within-k-stops/": "Airbnb, Amazon, Apple, Bloomberg, Google, Stripe, TikTok, Uber",
    "https://leetcode.com/problems/climbing-stairs/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/clone-graph/": "Amazon, Apple, Bloomberg, Google, Nvidia, Oracle, Uber",
    "https://leetcode.com/problems/coin-change-ii/": "Amazon, Bloomberg, Google, Salesforce, TikTok",
    "https://leetcode.com/problems/coin-change/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/combination-sum-ii/": "Adobe, Amazon, Bloomberg, Google, Meta, Microsoft, Oracle, TikTok",
    "https://leetcode.com/problems/combination-sum-iii/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/combination-sum-iv/": "Amazon, Bloomberg, Google, TikTok",
    "https://leetcode.com/problems/combination-sum/": "Airbnb, Amazon, Apple, Bloomberg, Google, LinkedIn, Meta, Microsoft, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/combinations/": "Amazon, Bloomberg, Google, Meta, Microsoft, TikTok",
    "https://leetcode.com/problems/concatenation-of-array/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/": "Adobe, Amazon, Bloomberg, Google, Meta, Salesforce, TikTok",
    "https://leetcode.com/problems/construct-quad-tree/": "Amazon, Bloomberg, Google, Uber",
    "https://leetcode.com/problems/container-with-most-water/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/contains-duplicate-ii/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, Google, Netflix",
    "https://leetcode.com/problems/contains-duplicate/": "Airbnb, Amazon, Apple, Bloomberg, Google, Netflix, Nvidia, Oracle",
    "https://leetcode.com/problems/copy-list-with-random-pointer/": "Amazon, Apple, Bloomberg, Google, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/count-good-nodes-in-binary-tree/": "Amazon, Goldman Sachs, Google",
    "https://leetcode.com/problems/counting-bits/": "Amazon, Apple, Bloomberg, Google, Nvidia, Oracle",
    "https://leetcode.com/problems/course-schedule-ii/": "Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Netflix, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/course-schedule-iv/": "Amazon, Google, TikTok, Uber",
    "https://leetcode.com/problems/course-schedule/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/daily-temperatures/": "Amazon, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, TikTok",
    "https://leetcode.com/problems/decode-string/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok",
    "https://leetcode.com/problems/decode-ways/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/delete-leaves-with-a-given-value": "Amazon, Google",
    "https://leetcode.com/problems/delete-node-in-a-bst/": "Amazon, Bloomberg, Google, Oracle, Uber",
    "https://leetcode.com/problems/design-circular-queue/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle",
    "https://leetcode.com/problems/design-hashmap/": "Amazon, Apple, Goldman Sachs, Google, Oracle, TikTok",
    "https://leetcode.com/problems/design-hashset/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/design-twitter/": "Adobe, Amazon, Apple, Bloomberg, Google, Salesforce, Uber",
    "https://leetcode.com/problems/detect-squares/": "Amazon, Google",
    "https://leetcode.com/problems/diameter-of-binary-tree/": "Amazon, Apple, Bloomberg, DoorDash, Google, LinkedIn, Nvidia, Oracle, TikTok",
    "https://leetcode.com/problems/distinct-subsequences/": "Amazon, Bloomberg, Google, Oracle, Salesforce",
    "https://leetcode.com/problems/dota2-senate/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/edit-distance/": "Amazon, Apple, Bloomberg, Google, LinkedIn, Meta, Microsoft, Oracle, TikTok",
    "https://leetcode.com/problems/encode-and-decode-strings/": "Amazon, Google, Oracle, TikTok",
    "https://leetcode.com/problems/evaluate-division/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Stripe, TikTok, Uber",
    "https://leetcode.com/problems/evaluate-reverse-polish-notation/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Oracle",
    "https://leetcode.com/problems/excel-sheet-column-title/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/extra-characters-in-a-string/": "Amazon, Google",
    "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/": "Amazon, Google, Uber",
    "https://leetcode.com/problems/find-in-mountain-array": "Amazon, Bloomberg, Google, Oracle",
    "https://leetcode.com/problems/find-k-closest-elements/": "Amazon, Apple, Bloomberg, DoorDash, Google, LinkedIn, Nvidia, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/find-median-from-data-stream/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/find-the-duplicate-number/": "Amazon, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok",
    "https://leetcode.com/problems/find-the-town-judge": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/first-missing-positive/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Netflix, Oracle, Salesforce",
    "https://leetcode.com/problems/gas-station/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Oracle, Salesforce, TikTok",
    "https://leetcode.com/problems/generate-parentheses/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/graph-valid-tree/": "Amazon, Google, LinkedIn, TikTok, Uber",
    "https://leetcode.com/problems/greatest-common-divisor-of-strings/": "Amazon, Bloomberg, Google, Oracle, TikTok",
    "https://leetcode.com/problems/group-anagrams/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/guess-number-higher-or-lower/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/hand-of-straights/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/happy-number/": "Airbnb, Amazon, Apple, Bloomberg, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/house-robber-ii/": "Amazon, Apple, Bloomberg, Google, LinkedIn, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/house-robber-iii/": "Amazon, Bloomberg, Google, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/house-robber/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/implement-stack-using-queues/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google",
    "https://leetcode.com/problems/implement-trie-prefix-tree/": "Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/insert-greatest-common-divisors-in-linked-list/": "Bloomberg, Google",
    "https://leetcode.com/problems/insert-interval/": "Amazon, Apple, Bloomberg, Google, LinkedIn, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/insert-into-a-binary-search-tree/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/integer-break/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/interleaving-string/": "Amazon, Apple, Bloomberg, Google, Microsoft",
    "https://leetcode.com/problems/invert-binary-tree/": "Amazon, Bloomberg, Google, Oracle",
    "https://leetcode.com/problems/ipo/": "Amazon, Bloomberg, Google, Uber",
    "https://leetcode.com/problems/island-perimeter/": "Amazon, Apple, Bloomberg, Google, Oracle",
    "https://leetcode.com/problems/jump-game-ii/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Meta, Microsoft, Oracle, TikTok",
    "https://leetcode.com/problems/jump-game-vii/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/jump-game/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, TikTok",
    "https://leetcode.com/problems/k-closest-points-to-origin/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Oracle, Salesforce",
    "https://leetcode.com/problems/koko-eating-bananas/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Netflix, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/kth-largest-element-in-a-stream/": "Adobe, Amazon, Bloomberg, Goldman Sachs, Google, Salesforce",
    "https://leetcode.com/problems/kth-largest-element-in-an-array/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/kth-smallest-element-in-a-bst/": "Amazon, Bloomberg, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/largest-rectangle-in-histogram/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Meta, Microsoft, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/last-stone-weight-ii/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/last-stone-weight/": "Amazon, Bloomberg, Google, Nvidia, Oracle, Salesforce",
    "https://leetcode.com/problems/lemonade-change/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/letter-combinations-of-a-phone-number/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Oracle, Uber",
    "https://leetcode.com/problems/lfu-cache/": "Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Netflix, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/linked-list-cycle/": "Amazon, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle",
    "https://leetcode.com/problems/longest-common-prefix/": "Adobe, Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/longest-common-subsequence/": "Amazon, Apple, Bloomberg, DoorDash, Google, Salesforce, TikTok",
    "https://leetcode.com/problems/longest-consecutive-sequence/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/longest-happy-string/": "Amazon, Bloomberg, Google, TikTok",
    "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Google, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/longest-increasing-subsequence/": "Amazon, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/longest-palindromic-substring/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/longest-repeating-character-replacement/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Uber",
    "https://leetcode.com/problems/longest-substring-without-repeating-characters/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Netflix, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/longest-turbulent-subarray/": "Amazon, Google",
    "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/": "Amazon, Apple, Bloomberg, Google, LinkedIn",
    "https://leetcode.com/problems/lru-cache/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Netflix, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/majority-element-ii": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/majority-element/": "Adobe, Amazon, Bloomberg, Goldman Sachs, Google, Oracle",
    "https://leetcode.com/problems/matchsticks-to-square/": "Amazon, Google, TikTok, Uber",
    "https://leetcode.com/problems/max-area-of-island/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Oracle, TikTok",
    "https://leetcode.com/problems/maximum-depth-of-binary-tree/": "Amazon, Apple, Bloomberg, Google, LinkedIn, Meta, Microsoft, Oracle, Uber",
    "https://leetcode.com/problems/maximum-frequency-stack/": "Amazon, Apple, Bloomberg, Google, Salesforce, Uber",
    "https://leetcode.com/problems/maximum-product-subarray/": "Adobe, Amazon, Bloomberg, Goldman Sachs, Google, LinkedIn, Nvidia, Salesforce, TikTok",
    "https://leetcode.com/problems/maximum-subarray/": "Airbnb, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/maximum-sum-circular-subarray/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, TikTok",
    "https://leetcode.com/problems/median-of-two-sorted-arrays/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/meeting-rooms-ii/": "Adobe, Amazon, Apple, Bloomberg, Google, Netflix, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/meeting-rooms-iii": "Amazon, Bloomberg, Goldman Sachs, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/meeting-rooms/": "Amazon, Apple, Bloomberg, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/merge-intervals/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Netflix, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/merge-k-sorted-lists/": "Airbnb, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/merge-sorted-array/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle",
    "https://leetcode.com/problems/merge-strings-alternately/": "Amazon, Bloomberg, Google, Oracle, Uber",
    "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/": "Google",
    "https://leetcode.com/problems/merge-two-sorted-lists/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok",
    "https://leetcode.com/problems/min-cost-climbing-stairs/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/min-cost-to-connect-all-points/": "Amazon, Google, TikTok, Uber",
    "https://leetcode.com/problems/min-stack/": "Adobe, Amazon, Apple, Bloomberg, Google, LinkedIn, Nvidia, Oracle, Salesforce, Uber",
    "https://leetcode.com/problems/minimum-array-end/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/minimum-height-trees": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/minimum-interval-to-include-each-query/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/minimum-path-sum/": "Amazon, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, TikTok, Uber",
    "https://leetcode.com/problems/minimum-size-subarray-sum/": "Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Nvidia, Oracle, TikTok",
    "https://leetcode.com/problems/minimum-window-substring/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/missing-number/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, Salesforce",
    "https://leetcode.com/problems/multiply-strings/": "Amazon, Bloomberg, Google, Meta, Microsoft, Oracle, TikTok",
    "https://leetcode.com/problems/n-queens-ii/": "Amazon, Bloomberg, Google, Microsoft",
    "https://leetcode.com/problems/n-queens/": "Adobe, Amazon, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, TikTok",
    "https://leetcode.com/problems/n-th-tribonacci-number/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/network-delay-time/": "Amazon, Bloomberg, Google, Netflix, Nvidia, Salesforce",
    "https://leetcode.com/problems/non-overlapping-intervals/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Oracle, TikTok",
    "https://leetcode.com/problems/number-of-1-bits/": "Amazon, Apple, Bloomberg, Google, Nvidia",
    "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/": "Amazon, Google, LinkedIn, TikTok",
    "https://leetcode.com/problems/number-of-islands/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/online-stock-span/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/open-the-lock/": "Amazon, Bloomberg, Goldman Sachs, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/pacific-atlantic-water-flow/": "Adobe, Amazon, Bloomberg, Google, TikTok",
    "https://leetcode.com/problems/palindrome-partitioning/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/palindromic-substrings/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Oracle, Salesforce",
    "https://leetcode.com/problems/partition-equal-subset-sum/": "Amazon, Bloomberg, Goldman Sachs, Google, Salesforce, TikTok",
    "https://leetcode.com/problems/partition-labels/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/": "Amazon, Bloomberg, Google, LinkedIn, TikTok",
    "https://leetcode.com/problems/path-with-minimum-effort/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/perfect-squares/": "Amazon, Bloomberg, Goldman Sachs, Google",
    "https://leetcode.com/problems/permutation-in-string/": "Adobe, Amazon, Apple, Bloomberg, Google, Oracle, TikTok",
    "https://leetcode.com/problems/permutations-ii/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, TikTok",
    "https://leetcode.com/problems/permutations/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/plus-one/": "Amazon, Bloomberg, Google, Meta, Microsoft, TikTok",
    "https://leetcode.com/problems/powx-n/": "Adobe, Amazon, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, TikTok",
    "https://leetcode.com/problems/product-of-array-except-self/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Nvidia, Oracle, Salesforce, Uber",
    "https://leetcode.com/problems/range-sum-query-2d-immutable/": "Amazon, Bloomberg, DoorDash, Google, Salesforce",
    "https://leetcode.com/problems/reconstruct-itinerary/": "Adobe, Amazon, Apple, Bloomberg, Google, Netflix, Salesforce, Uber",
    "https://leetcode.com/problems/redundant-connection/": "Amazon, Bloomberg, Google, Oracle",
    "https://leetcode.com/problems/regular-expression-matching/": "Airbnb, Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/remove-duplicates-from-sorted-array/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, Uber",
    "https://leetcode.com/problems/remove-element/": "Adobe, Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Uber",
    "https://leetcode.com/problems/remove-nth-node-from-end-of-list/": "Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Oracle, TikTok",
    "https://leetcode.com/problems/reorder-list/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, TikTok",
    "https://leetcode.com/problems/reorganize-string/": "Amazon, Bloomberg, Goldman Sachs, Google, Oracle, Salesforce, TikTok",
    "https://leetcode.com/problems/reverse-bits/": "Airbnb, Amazon, Apple, Bloomberg, Google, Nvidia",
    "https://leetcode.com/problems/reverse-integer/": "Adobe, Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Oracle, Uber",
    "https://leetcode.com/problems/reverse-linked-list-ii/": "Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Nvidia, Oracle, TikTok",
    "https://leetcode.com/problems/reverse-linked-list/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/reverse-nodes-in-k-group/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/reverse-string/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia",
    "https://leetcode.com/problems/roman-to-integer/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Meta, Microsoft, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/rotate-array/": "Amazon, Apple, Bloomberg, Google, Oracle, TikTok",
    "https://leetcode.com/problems/rotate-image/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/rotting-oranges/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/same-tree/": "Amazon, Apple, Bloomberg, Google, LinkedIn, Meta, Microsoft",
    "https://leetcode.com/problems/search-a-2d-matrix/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/": "Amazon, Bloomberg, Google, Meta, Microsoft",
    "https://leetcode.com/problems/search-in-rotated-sorted-array/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/search-insert-position/": "Amazon, Bloomberg, Google, Meta, Microsoft",
    "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/": "Amazon, Apple, Bloomberg, DoorDash, Google, LinkedIn, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/set-matrix-zeroes/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Uber",
    "https://leetcode.com/problems/simplify-path/": "Amazon, Apple, Bloomberg, Google, Meta, Microsoft, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/single-number/": "Adobe, Airbnb, Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/single-threaded-cpu/": "Amazon, DoorDash, Goldman Sachs, Google",
    "https://leetcode.com/problems/sliding-window-maximum/": "Adobe, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/sort-an-array/": "Amazon, Apple, Bloomberg, Google, Oracle",
    "https://leetcode.com/problems/sort-colors/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/spiral-matrix/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/split-array-largest-sum/": "Amazon, Bloomberg, Goldman Sachs, Google, Oracle, Uber",
    "https://leetcode.com/problems/sqrtx/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/stone-game-ii/": "Amazon, Bloomberg, Google, Uber",
    "https://leetcode.com/problems/stone-game-iii/": "Google",
    "https://leetcode.com/problems/stone-game/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/subarray-sum-equals-k/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/subsets-ii/": "Amazon, Apple, Bloomberg, Google, Meta, Microsoft",
    "https://leetcode.com/problems/subsets/": "Amazon, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/subtree-of-another-tree/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/sum-of-all-subset-xor-totals": "Adobe, Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/sum-of-two-integers/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/surrounded-regions/": "Adobe, Amazon, Bloomberg, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/swim-in-rising-water/": "Amazon, DoorDash, Google, Uber",
    "https://leetcode.com/problems/target-sum/": "Amazon, Bloomberg, Google",
    "https://leetcode.com/problems/task-scheduler/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Nvidia, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/time-based-key-value-store/": "Airbnb, Amazon, Apple, Bloomberg, Google, Netflix, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/top-k-frequent-elements/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Netflix, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/transpose-matrix": "Amazon, Apple, Bloomberg, Google",
    "https://leetcode.com/problems/trapping-rain-water/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/": "Adobe, Amazon, Apple, Bloomberg, Google, Oracle, TikTok",
    "https://leetcode.com/problems/two-sum/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, DoorDash, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/unique-paths-ii/": "Amazon, Bloomberg, Google, Meta, Microsoft, Nvidia, TikTok",
    "https://leetcode.com/problems/unique-paths/": "Amazon, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Nvidia, TikTok",
    "https://leetcode.com/problems/valid-anagram/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Netflix, Nvidia, Oracle, Uber",
    "https://leetcode.com/problems/valid-palindrome-ii/": "Amazon, Apple, Bloomberg, Google, TikTok, Uber",
    "https://leetcode.com/problems/valid-palindrome/": "Adobe, Amazon, Apple, Bloomberg, Google, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/valid-parentheses/": "Adobe, Airbnb, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Nvidia, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/valid-parenthesis-string/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Salesforce, TikTok",
    "https://leetcode.com/problems/valid-sudoku/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/validate-binary-search-tree/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Meta, Microsoft, Oracle, Salesforce",
    "https://leetcode.com/problems/verifying-an-alien-dictionary/": "Amazon, Apple, Bloomberg, Google, Uber",
    "https://leetcode.com/problems/walls-and-gates/": "Amazon, Bloomberg, DoorDash, Google, TikTok, Uber",
    "https://leetcode.com/problems/word-break-ii": "Amazon, Bloomberg, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/word-break/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Netflix, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/word-ladder/": "Adobe, Amazon, Apple, Bloomberg, Goldman Sachs, Google, LinkedIn, Oracle, Salesforce, TikTok, Uber",
    "https://leetcode.com/problems/word-search-ii/": "Airbnb, Amazon, Apple, Bloomberg, DoorDash, Google, Oracle, TikTok, Uber",
    "https://leetcode.com/problems/word-search/": "Amazon, Apple, Bloomberg, Goldman Sachs, Google, Meta, Microsoft, Netflix, Oracle, Salesforce, TikTok, Uber",
}
